export const translations={
    ES:{
        formMessage:'Por favor rellena este maravilloso formulario',
        formularyName: 'Nombre',
        formularySurname: 'Apellido',
        formularyPassword: 'Contraseña',
        languageSelection: 'Selecciona tu sabor favorito',
        submitValue:'Enviar',
        greetingUser:'Hola querido',
        midphrase:'Veo que te gusta',
        wishes:'Espero que disfrutes de esta grandiosa web tan bien estilizada' ,
        register:'Registro',
        profile:'Perfil',
        home:'Principal',
    },
    EN:{
        formMessage: 'Please fill this wonderful formulary',
        formularyName: 'Name',
        formularySurname: 'Surname',
        formularyPassword: 'Password',
        languageSelection: 'Select your favourite flavour',
        submitValue:'Send',
        greetingUser:'Hello sweety',
        midphrase:'I see you like',
        wishes:'I hope you enjoy this beautiful and such stylish web site',
        register:'Register',
        profile:'Profile',
        home:'Home',
    }
}